CREATE VIEW tytdata.tb_bd_quote_daily (
    c_trade_date      COMMENT '交易日期',
    c_bd_code         COMMENT '债券代码',
    c_bd_inner_code   COMMENT '债券内码',
    c_bd_name         COMMENT '债券简称',
    c_net_open        COMMENT '开盘净价(元)',
    c_net_close       COMMENT '收盘净价(元)',
    c_net_high        COMMENT '最高净价(元)',
    c_net_low         COMMENT '最低净价(元)',
    c_net_pre_close   COMMENT '前收盘净价(元)',
    c_net_chg_rate    COMMENT '净价涨跌幅(%)',
    c_full_open       COMMENT '开盘全价(元)',
    c_full_close      COMMENT '收盘全价(元)',
    c_full_high       COMMENT '最高全价(元)',
    c_full_low        COMMENT '最低全价(元)',
    c_full_avg        COMMENT '全价加权均价(元)',
    c_full_pre_close  COMMENT '前收盘全价(元)',
    c_volume          COMMENT '成交量',
    c_amount          COMMENT '成交金额(元)',
    c_trade_num       COMMENT '成交笔数',
    c_ytm_close       COMMENT '收盘到期收益率(%)',
    c_ytm_chg         COMMENT '收益率涨跌(BP)'
) COMMENT '债券日行情' AS
SELECT
    TDATE                AS c_trade_date,
    BONDCODE             AS c_bd_code,
    SECURITYVARIETYCODE  AS c_bd_inner_code,
    SNAME                AS c_bd_name,
    COPEN                AS c_net_open,
    CCLOSE               AS c_net_close,
    CHIGH                AS c_net_high,
    CLOW                 AS c_net_low,
    LCCLOSE              AS c_net_pre_close,
    CCHGRATE             AS c_net_chg_rate,
    FOPEN                AS c_full_open,
    FCLOSE               AS c_full_close,
    FHIGH                AS c_full_high,
    FLOW                 AS c_full_low,
    FAVG                 AS c_full_avg,
    LFCLOSE              AS c_full_pre_close,
    TVOL                 AS c_volume,
    TVAL                 AS c_amount,
    TNUM                 AS c_trade_num,
    CYTM                 AS c_ytm_close,
    YCHG                 AS c_ytm_chg
FROM TYTFUND.BOND_TD_DAILY
WHERE EISDEL = '0'
