CREATE VIEW tytdata.tb_fd_asset_allocation (
    -- ========== 基础信息 ==========
    c_fd_code COMMENT '基金代码',
    c_inner_code COMMENT '基金内码',
    c_report_date COMMENT '报告日期',
    c_style COMMENT '报表类型',
    c_notice_date COMMENT '公告日期',
    c_fund_total_asset COMMENT '基金总资产',
    c_fund_nav_total COMMENT '基金净值总额',
    c_currency COMMENT '币种',
    c_remark COMMENT '备注',

    -- ========== 股票投资 ==========
    c_stk_total_mv COMMENT '股票投资市值合计',
    c_stk_total_ratio COMMENT '股票投资占净值比例',
    c_stk_index_mv COMMENT '指数化投资市值',
    c_stk_index_ratio COMMENT '指数化投资占净值比例',
    c_stk_active_mv COMMENT '积极投资市值',
    c_stk_active_ratio COMMENT '积极投资占净值比例',
    c_stk_equity_mv COMMENT '权益类投资市值',
    c_stk_equity_ratio COMMENT '权益类投资占净值比例',
    c_stk_preferred_mv COMMENT '优先股市值',
    c_stk_preferred_ratio COMMENT '优先股占净值比例',
    c_stk_hk_connect_mv COMMENT '港股通市值',
    c_stk_hk_connect_ratio COMMENT '港股通占净值比例',
    c_stk_lend_securities_mv COMMENT '转融通证券出借业务市值',
    c_stk_lend_securities_ratio COMMENT '转融通证券出借业务占净值比例',

    -- ========== 债券投资 ==========
    c_bd_total_mv COMMENT '债券市值合计',
    c_bd_total_ratio COMMENT '债券市值占净值比例',
    c_bd_convertible_mv COMMENT '可转换债券市值',
    c_bd_convertible_ratio COMMENT '可转债占净值比例',
    c_bd_treasury_mv COMMENT '国债市值',
    c_bd_treasury_ratio COMMENT '国债占净值比例',
    c_bd_financial_mv COMMENT '金融债市值',
    c_bd_financial_ratio COMMENT '金融债占净值比例',
    c_bd_policy_mv COMMENT '政策性金融债市值',
    c_bd_policy_ratio COMMENT '政策性金融债占净值比例',
    c_bd_local_gov_mv COMMENT '地方政府债市值',
    c_bd_local_gov_ratio COMMENT '地方政府债占净值比例',
    c_bd_corporate_mv COMMENT '企业债市值',
    c_bd_corporate_ratio COMMENT '企业债占净值比例',
    c_bd_short_term_mv COMMENT '企业短期融资券市值',
    c_bd_short_term_ratio COMMENT '企业短期融资券占净值比例',
    c_bd_mtn_mv COMMENT '中期票据市值',
    c_bd_mtn_ratio COMMENT '中期票据占净值比例',
    c_bd_central_bank_mv COMMENT '央行票据市值',
    c_bd_central_bank_ratio COMMENT '央行票据占净值比例',
    c_bd_deposit_cert_mv COMMENT '同业存单市值',
    c_bd_deposit_cert_ratio COMMENT '同业存单占净值比例',
    c_bd_fixed_income_mv COMMENT '固定收益类投资市值合计',
    c_bd_fixed_income_ratio COMMENT '固定收益类投资占净值比例',
    c_bd_float_over_397d_mv COMMENT '剩余存续期超过397天浮动利率债券市值',
    c_bd_float_over_397d_ratio COMMENT '剩余存续期超过397天浮动利率债券占净值比例',
    c_bd_other_mv COMMENT '其他债券市值',
    c_bd_other_ratio COMMENT '其他债券占净值比例',

    -- ========== 现金货币 ==========
    c_cash_total_mv COMMENT '货币资金合计',
    c_cash_total_ratio COMMENT '货币资金占净值比例',
    c_cash_deposit_mv COMMENT '银行存款',
    c_cash_deposit_ratio COMMENT '银行存款占净值比例',
    c_cash_market_tool_mv COMMENT '货币市场工具市值合计',
    c_cash_market_tool_ratio COMMENT '货币市场工具占净值比例',
    c_cash_settlement_mv COMMENT '清算备付金',
    c_cash_settlement_ratio COMMENT '清算备付金占净值比例',

    -- ========== 基金投资 ==========
    c_fd_inv_total_mv COMMENT '基金投资市值合计',
    c_fd_inv_total_ratio COMMENT '基金投资市值占净值比例',

    -- ========== 衍生品投资 ==========
    c_deriv_total_mv COMMENT '金融衍生品投资',
    c_deriv_total_ratio COMMENT '金融衍生品投资占净值比例',
    c_deriv_forward_mv COMMENT '远期投资市值',
    c_deriv_forward_ratio COMMENT '远期投资市值占净值比例',
    c_deriv_future_mv COMMENT '期货投资市值',
    c_deriv_future_ratio COMMENT '期货投资市值占净值比例',
    c_deriv_option_mv COMMENT '期权投资市值',
    c_deriv_option_ratio COMMENT '期权占净值比例',

    -- ========== 其他投资品种 ==========
    c_other_warrant_mv COMMENT '权证投资市值合计',
    c_other_warrant_ratio COMMENT '权证投资市值占净值比例',
    c_other_abs_mv COMMENT '资产支持证券市值合计',
    c_other_abs_ratio COMMENT '资产支持证券市值占净值比例',
    c_other_infra_abs_mv COMMENT '基础设施资产支持证券市值',
    c_other_infra_abs_ratio COMMENT '基础设施资产支持证券占净值比例',
    c_other_tdr_mv COMMENT '存托凭证市值合计',
    c_other_tdr_ratio COMMENT '存托凭证占净值比例',
    c_other_reits_mv COMMENT '房地产信托市值',
    c_other_reits_ratio COMMENT '房地产信托市值占净值比例',
    c_other_commodity_mv COMMENT '商品现货合约投资市值',
    c_other_commodity_ratio COMMENT '商品现货合约投资占净值比例',
    c_other_gold_mv COMMENT '黄金市值',
    c_other_gold_ratio COMMENT '黄金占净值比例',
    c_other_long_equity_mv COMMENT '长期股权投资',
    c_other_long_equity_ratio COMMENT '长期股权投资占净值比例',

    -- ========== 回购业务 ==========
    c_repo_buy_resell_mv COMMENT '买入返售金融资产',
    c_repo_buy_resell_ratio COMMENT '买入返售证券占净值比例',
    c_repo_sell_buy_mv COMMENT '卖出回购证券余额',
    c_repo_sell_buy_ratio COMMENT '卖出回购证券占净值比例',
    c_repo_buyout_mv COMMENT '买断式回购的买入返售金融资产',
    c_repo_buyout_ratio COMMENT '买断式回购的买入返售金融资产比例',

    -- ========== 应收款项 ==========
    c_recv_sec_clear_mv COMMENT '应收证券清算款',
    c_recv_sec_clear_ratio COMMENT '应收证券清算款占净值比例',
    c_recv_margin_mv COMMENT '交易保证金',
    c_recv_margin_ratio COMMENT '交易保证金占净值比例',
    c_recv_dividend_mv COMMENT '应收股利',
    c_recv_dividend_ratio COMMENT '应收股利占净值比例',
    c_recv_interest_mv COMMENT '应收利息',
    c_recv_interest_ratio COMMENT '应收利息占净值比例',
    c_recv_purchase_mv COMMENT '应收申购款',
    c_recv_purchase_ratio COMMENT '应收申购款占净值比例',
    c_recv_refund_mv COMMENT '应收退补款',
    c_recv_refund_ratio COMMENT '应收退补款占净值比例',
    c_recv_refund_collectable_mv COMMENT '可收退补款',
    c_recv_refund_collectable_ratio COMMENT '可收退补款占净值比例',
    c_recv_service_return_mv COMMENT '应收销售服务费返还',
    c_recv_service_return_ratio COMMENT '应收销售服务费返还占净值比例',
    c_recv_lend_interest_mv COMMENT '应计出借证券利息',
    c_recv_lend_interest_ratio COMMENT '应计出借证券利息占净值比例',

    -- ========== 其他杂项 ==========
    c_misc_debt_balance_mv COMMENT '贷方余额',
    c_misc_debt_balance_ratio COMMENT '贷方余额占净值比例',
    c_misc_other_inv_mv COMMENT '其他投资市值',
    c_misc_other_inv_ratio COMMENT '其他投资占净值比例',
    c_misc_deferred_exp_mv COMMENT '待摊费用',
    c_misc_deferred_exp_ratio COMMENT '待摊费用占净值比例',
    c_misc_other_recv_mv COMMENT '其他应收款',
    c_misc_other_recv_ratio COMMENT '其他应收款占净值比例',
    c_misc_other_asset_mv COMMENT '其他其他资产',
    c_misc_other_asset_ratio COMMENT '其他其他资产占净值比例',

    -- ========== 控制字段 ==========
    c_is_stat COMMENT '是否参与统计(-1主0分级)',
    c_is_sum COMMENT '是否为合并数据(1为是,0为否)'
) COMMENT '基金资产配置表' AS
SELECT
    -- ========== 基础信息 ==========
    FUNDCODE as c_fd_code,
    SECURITYVARIETYCODE as c_inner_code,
    ENDDATE as c_report_date,
    STYLE as c_style,
    NOTICEDATE as c_notice_date,
    FASSETSUM as c_fund_total_asset,
    FNVSUM as c_fund_nav_total,
    CURRENCY as c_currency,
    REMARK as c_remark,

    -- ========== 股票投资 ==========
    SIMVSUM as c_stk_total_mv,
    SIPCTNV as c_stk_total_ratio,
    INDEXIVALUE as c_stk_index_mv,
    IIPCTNV as c_stk_index_ratio,
    POSITIVALUE as c_stk_active_mv,
    PIPCTNV as c_stk_active_ratio,
    EQVALUE as c_stk_equity_mv,
    EQPCTNV as c_stk_equity_ratio,
    PSTKVALUE as c_stk_preferred_mv,
    PSTKPCTNV as c_stk_preferred_ratio,
    HKSK_CONNECT as c_stk_hk_connect_mv,
    HKSK_CONNECT_NR as c_stk_hk_connect_ratio,
    LEND_SECURITIES as c_stk_lend_securities_mv,
    LEND_SECURITIES_NR as c_stk_lend_securities_ratio,

    -- ========== 债券投资 ==========
    BSUM as c_bd_total_mv,
    BSPCTNV as c_bd_total_ratio,
    BONGTRANSFA as c_bd_convertible_mv,
    BTPCTNV as c_bd_convertible_ratio,
    NBONDV as c_bd_treasury_mv,
    NBPCTNV1 as c_bd_treasury_ratio,
    FINABV as c_bd_financial_mv,
    FINABVPCTNV as c_bd_financial_ratio,
    POLICYBOND as c_bd_policy_mv,
    PBPCTNV as c_bd_policy_ratio,
    LOCALGOV_BOND as c_bd_local_gov_mv,
    LOCALGOV_BOND_NR as c_bd_local_gov_ratio,
    CBV as c_bd_corporate_mv,
    CBVPCTNV as c_bd_corporate_ratio,
    CBSB as c_bd_short_term_mv,
    CBSBPCTNV as c_bd_short_term_ratio,
    MTN as c_bd_mtn_mv,
    MTNPCTNV as c_bd_mtn_ratio,
    CBB as c_bd_central_bank_mv,
    CBBPCTNV as c_bd_central_bank_ratio,
    DEPOSITCE as c_bd_deposit_cert_mv,
    DEPOSITCEPCT as c_bd_deposit_cert_ratio,
    FIVALUE_IMC as c_bd_fixed_income_mv,
    FIVALUE_IMC_NAVRATIO as c_bd_fixed_income_ratio,
    FLOATB397 as c_bd_float_over_397d_mv,
    FB397PCTNV as c_bd_float_over_397d_ratio,
    OTHERBOND as c_bd_other_mv,
    OBPCTNV as c_bd_other_ratio,

    -- ========== 现金货币 ==========
    MSUM as c_cash_total_mv,
    MPCTNV as c_cash_total_ratio,
    DEPOSIT as c_cash_deposit_mv,
    DSTPCTNV as c_cash_deposit_ratio,
    MTOOLSUM as c_cash_market_tool_mv,
    MTSPCTNV as c_cash_market_tool_ratio,
    SETTLECOVER as c_cash_settlement_mv,
    SCPCTNV as c_cash_settlement_ratio,

    -- ========== 基金投资 ==========
    FINVESTSUM as c_fd_inv_total_mv,
    FISPCTNV as c_fd_inv_total_ratio,

    -- ========== 衍生品投资 ==========
    FINADERIV as c_deriv_total_mv,
    FDPCTNV as c_deriv_total_ratio,
    LONGTERMIVEST as c_deriv_forward_mv,
    LTIPCTNV as c_deriv_forward_ratio,
    FUTURE as c_deriv_future_mv,
    FTPCTNV as c_deriv_future_ratio,
    OPTIONFUND as c_deriv_option_mv,
    OPTIONPCTNV as c_deriv_option_ratio,

    -- ========== 其他投资品种 ==========
    WARRANTSUM as c_other_warrant_mv,
    WSPCTNV as c_other_warrant_ratio,
    ABSSUM as c_other_abs_mv,
    ABSPCTNV as c_other_abs_ratio,
    INFRASTRUCTURE_ABS as c_other_infra_abs_mv,
    INFRASTRUCTURE_ABS_NR as c_other_infra_abs_ratio,
    TDRSUM as c_other_tdr_mv,
    TDRSPCTNV as c_other_tdr_ratio,
    REITSVALUE as c_other_reits_mv,
    REITSPCTNV as c_other_reits_ratio,
    SPOTCTRTVALUE as c_other_commodity_mv,
    SPOTCTRTPCT as c_other_commodity_ratio,
    GOLDCTRTVALUE as c_other_gold_mv,
    GOLDCTRTPCT as c_other_gold_ratio,
    LONG_EQUITY_INVEST as c_other_long_equity_mv,
    LONG_EQUITY_INVESTNR as c_other_long_equity_ratio,

    -- ========== 回购业务 ==========
    BREPO as c_repo_buy_resell_mv,
    BREPOPCTNV as c_repo_buy_resell_ratio,
    SREPO as c_repo_sell_buy_mv,
    SREPOPCTNV as c_repo_sell_buy_ratio,
    REPOASSET as c_repo_buyout_mv,
    RAPCTNV as c_repo_buyout_ratio,

    -- ========== 应收款项 ==========
    RCVASECUCLEAR as c_recv_sec_clear_mv,
    RSCPCTNV as c_recv_sec_clear_ratio,
    BAIL as c_recv_margin_mv,
    BAILPCTNV as c_recv_margin_ratio,
    RCVABONUS as c_recv_dividend_mv,
    RVABPCTNV as c_recv_dividend_ratio,
    RCVAINTEREST as c_recv_interest_mv,
    RVAIPCTNV as c_recv_interest_ratio,
    RVAAP as c_recv_purchase_mv,
    RVAAPPCTNV as c_recv_purchase_ratio,
    REFUND_RECE as c_recv_refund_mv,
    REFUND_RECE_NR as c_recv_refund_ratio,
    REFUND_RECO as c_recv_refund_collectable_mv,
    REFUND_RECO_NR as c_recv_refund_collectable_ratio,
    SERVICE_RETURN_RECE as c_recv_service_return_mv,
    SERVICERETURN_RECE_NR as c_recv_service_return_ratio,
    ACCRUAL_LEND_INTEREST as c_recv_lend_interest_mv,
    ACCRUAL_LENDINTEREST_NR as c_recv_lend_interest_ratio,

    -- ========== 其他杂项 ==========
    DEBTBALANCE as c_misc_debt_balance_mv,
    DBPCTNV as c_misc_debt_balance_ratio,
    OINVSTV as c_misc_other_inv_mv,
    OIPCTNV as c_misc_other_inv_ratio,
    DEFFEREXP as c_misc_deferred_exp_mv,
    DEXPPCTNV as c_misc_deferred_exp_ratio,
    ORVA as c_misc_other_recv_mv,
    ORVAPCTNV as c_misc_other_recv_ratio,
    OOASSETS as c_misc_other_asset_mv,
    OOAPCTNV as c_misc_other_asset_ratio,

    -- ========== 控制字段 ==========
    ISSTAT as c_is_stat,
    ISSUM as c_is_sum
FROM TYTFUND.FUND_IV_ASSETALLOCT
WHERE EISDEL = '0'